### ISSUE TITLE
make each membership public (as long as it is ok)

### ISSUE THREAD

**Issue by hfu** [foss4g-tokyo-vt/living-room#1]
I think it would be good to make each membership visibility to 'public'.
@smellman, @mapconcierge, please do so by yourself at https://github.com/orgs/foss4g-tokyo-vt/people if you think it is ok to do so.
<img width="990" alt="2015-10-06 14 58 38" src="https://cloud.githubusercontent.com/assets/18297/10301269/9041c5f2-6c3b-11e5-917f-2f8a68b56414.png">

メンバーシップの可視性を public にしたほうが素敵だと思います。ユーザ自身しかそのユーザの可視性を変更できないので、もし public にしても構わないようでしたら、各自で変更いただけるでしょうか。

**Comment by mapconcierge** [comment]
＞ @hfu 
Done!! :-)
![2015-10-08 6 17 20](https://cloud.githubusercontent.com/assets/416977/10351400/56c8f5bc-6d84-11e5-9c6e-0f8a49dde93c.png)

**Comment by hfu** [comment]
> @mapconcierge @smellman 
> Thank you! :+1:
