### ISSUE TITLE
Invite more members

### ISSUE THREAD

**Issue by hfu** [foss4g-tokyo-vt/living-room#2]
FOSS4G 2015 Tokyo のハンズオンの文脈をオンラインで継続するために、この organization アカウントへのメンバーに招待を進めようと思います。

具体的には、ハンズオンの中でご案内します。

手続きは次のようにしたいと思います。
1.  参加しても良いという方は、この issue に「メンバー登録してください」とコメントしてください。
2. この organization の Owners グループの人が、適宜その方を Owners グループのメンバーに追加し、コメントに返信します。
3. 参加したメンバーの方は、https://github.com/orgs/foss4g-tokyo-vt/people から、自分の visibility を public に変更してください。

メンバーシップの扱いは、次のようにしたいと思います。
1. メンバーシップの義務は、メンバーシップを持つこと、メンバーシップの特典は、メンバーシップを持てることであるとします。つまり、その他の権利義務関係を発生するものではないものとします。
2. この organization の扱いに議論の必要が生じた場合には、レポジトリ内での議論によって議論を進めることとするが、議論が収束しない場合などの場合に最終的に判断を行うのは organization 作成者の @hfu とする（veto の付与）。

それでは、参加を希望してくださる方は、コメントをお願いします。

**Comment by kurohune538** [comment]
メンバー登録してください！

**Comment by Kenyat1989** [comment]
メンバー登録してください

**Comment by mapconcierge** [comment]
＞ @kurohune538 
登録しました！

**Comment by mapconcierge** [comment]
＞ @Kenyat1989 
登録しました！

**Comment by mapconcierge** [comment]
＞ @Kenyat1989 @kurohune538 
invitation メールを確認お願いします！

**Comment by mapconcierge** [comment]
＞ @kurohune538 さん
https://github.com/orgs/foss4g-tokyo-vt/people から、自分の visibility を public に変更お願いします。

**Comment by Kenyat1989** [comment]
確認しましたー！
ありがとうございます！

**Comment by tohka** [comment]
本日はありがとうございました。
登録をお願いします。

**Comment by hfu** [comment]
> @tohka 
> ありがとうございます。invite 送りましたので確認ください。また、https://github.com/orgs/foss4g-tokyo-vt/people から、自分の visibility を public に変更お願いします。

**Comment by hfu** [comment]
※ Issue のリストを長くしすぎないようにするため、この issue は10月14日23:59を過ぎた適当のタイミングで、自動的に close としたいと思います。close 作業は @hfu にアサインということで。引き続き、参加招待の作業は、既存メンバーの皆さまに積極的に実施いただけるとありがたいです。

**Comment by valuecreation** [comment]
メンバー登録お願い致します！

**Comment by hfu** [comment]
@ValueCreation ,
ありがとうございます。invite 送りましたので確認ください。また、https://github.com/orgs/foss4g-tokyo-vt/people から、自分の visibility を public に変更お願いします。

**Comment by valuecreation** [comment]
確認しました。また、publicに変更しました。
ありがとうございます。

**Comment by tkmoda** [comment]
先日はありがとうございました。
メンバー登録をお願いします！

**Comment by hfu** [comment]
@tkmoda ,
ありがとうございます。invite 送りましたので確認ください。また、https://github.com/orgs/foss4g-tokyo-vt/people から、自分の visibility を public に変更お願いします。

**Comment by tkmoda** [comment]
よく見たら14日クローズでした。
登録ありがとうございます！
publicに変更しました。

**Comment by hfu** [comment]
@tkmoda ありがとうございます。この issue は expire ということで一旦 close にしますが、メンバー登録をしてみたいという方が他にいらっしゃいましたら、遠慮なく reopen してください。ありがとうございました.
