### ISSUE TITLE
作品集

### ISSUE THREAD

**Issue by mapconcierge** [foss4g-tokyo-vt/living-room#3]
参加者のみなさんの作品を共有するISSUEスレッドです。
画像ファイルはファイルアイコンをドラッグするとアップロードできます。

**Comment by mapconcierge** [comment]
picaosgeoさんの「地底領土」GeoJSON
http://picaosgeo.github.io/gsimaps/#5/37.282795/135.263672

![2015-10-09 16 36 29](https://cloud.githubusercontent.com/assets/416977/10388403/a6650630-6ea4-11e5-8e67-8ec393f7bd68.png)

**Comment by hfu** [comment]
ありがとうございます。
https://github.com/foss4g-tokyo-vt/living-room/blob/master/links.md
との使い分けについて、あるいは作品集に markdown のページを使うのと issue を使うのとどちらが有利か、ということを考えています。

issue を使うと、 @mapconcierge がされたようにスクリーンショットが置けるのが有利ですね。
markdown で置いておくと、issue と違って情報が流れないのが有利です。あと、close することを想定していない issue、というものの存在をどう割り切るかという論点があると思います。

foss4g-tokyo-vt はハンズオンのための実験的な organization なので、ここをご覧になった皆さまそれぞれで比較検討していただき、経験としていただければ幸いです。

**Comment by mapconcierge** [comment]
＞ @hfu 
個人的な使い分けは、issue のほうを、プルリクエストに慣れていない人向けと投稿用で、スクリーンキャプチャを簡単に共有できる点ですね。最終的に整理した情報を markdown ページに掲載していくのがわかりやすいと思っています。

**Comment by hfu** [comment]
> @mapconcierge 
> 拝承。Issue の利便性と .md の安定性の両立ですね。

**Comment by hfu** [comment]
こちらも、特段現状を変える必要なし、ということでクローズにします。
